# connect with https://www.mongodb.com/docs/mongodb-shell/
# brew install mongosh
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: scnace
      MONGO_INITDB_ROOT_PASSWORD: scnace
    ports:
      - 27017:27017
    command:
    - --storageEngine
    - wiredTiger
